[build-system]

requires = ["setuptools>=61","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "matrix"
version="0.0.1"
requires-python = ">=3.10"


[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

